### ISSUE TITLE
currentUserImageURLWithSize doesn't work: Invalid type passed to function

### ISSUE THREAD

**Issue by chmiiller** [hansemannn/ti.googlesignin#2]
Hi @hansemannn ,
I'm getting:
```
"nativeLocation": "-[TiGooglesigninModule currentUserImageURLWithSize:] (TiGooglesigninModule.m:171)",
  "message": "Invalid type passed to function",
  "nativeReason": "expected: Number, was: Array",
```

when using:
```
var profileURL = Google.currentUserImageURLWithSize(200);
```

The problem is happening on this line on TiGooglesigninModule.m, line 173:
```
return [[[[[GIDSignIn sharedInstance] currentUser] profile] imageURLWithDimension:[TiUtils intValue:size]] absoluteString];
```

Noticed that you're using `ENSURE_TYPE(size, NSNumber);` but can't understand why it is complaining that we're passing an array instead of a number.
Can you think in a reason for that?

Thanks!

**Comment by hansemannn** [comment]
Whoops. Fixed in latest commit.

**Comment by chmiiller** [comment]
great, tested and working!

**Comment by hansemannn** [comment]
Sorry about those small bugs, the whole module done in basically 2 hours.
